ASSETS_PATH = 'C:/Users/DELL/PycharmProjects/Mario-Quest/assets'
MENU_PATH = f'{ASSETS_PATH}/images/menu'
MAIN_PATH = f'{ASSETS_PATH}/images/main'
MARIO_PATH = f'{ASSETS_PATH}/images/mario'
SFX_PATH = f'{ASSETS_PATH}/sfx'
